permissions:
  contents: write
  pages: write
  id-token: write

name: Pages
on:
  push:
    branches:
    - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install package
      run: sudo apt-get -y install libosmesa6-dev libgl1-mesa-dev git-restore-mtime
    - name: Install project requirements
      run: pip install -r requirements.txt
    - name: Build HTML
      run: |
        panel convert enodise_database.py
        mv enodise_database.html index.html
    - name: Run ghp-import
      run: | 
        ls -l
        ghp-import -n -p -f .
