permissions:
  contents: write
  pages: write
  id-token: write

name: Pages
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install project requirements
      run: pip install -r requirements.txt
    - name: Build HTML
      run: |
        mkdir doc
        panel convert enodise_database.py --to pyscript --out doc --disable-http-patch
        mv doc/enodise_database.html doc/index.html
        cp enodise_database.csv doc
        ls doc
    - name: Run ghp-import
      run: | 
        ls -l
        ghp-import -n -p -f doc
